/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param startDateLocal 
 * @param type 
 * @param name 
 */
@JsonClass(generateAdapter = true)

data class ActivityMini (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "start_date_local")
    val startDateLocal: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null

)

