/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model

import com.github.maciej.kaznowski.intervalsicuclient.model.Pos

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param power 
 * @param hr 
 * @param pace 
 * @param `data` 
 */
@JsonClass(generateAdapter = true)

data class ActivityCharts (

    @Json(name = "power")
    val power: kotlin.collections.List<Pos>? = null,

    @Json(name = "hr")
    val hr: kotlin.collections.List<Pos>? = null,

    @Json(name = "pace")
    val pace: kotlin.collections.List<Pos>? = null,

    @Json(name = "data")
    val `data`: kotlin.collections.List<Pos>? = null

)

