/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param startDateLocal 
 * @param weight 
 * @param bpm 
 */
@JsonClass(generateAdapter = true)

data class ActivityHRCurve (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "start_date_local")
    val startDateLocal: kotlin.String? = null,

    @Json(name = "weight")
    val weight: kotlin.Float? = null,

    @Json(name = "bpm")
    val bpm: kotlin.collections.List<kotlin.Int>? = null

)

