/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param fieldId 
 * @param code 
 * @param `operator` 
 * @param `value` 
 * @param not 
 */
@JsonClass(generateAdapter = true)

data class ActivityFilter (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "field_id")
    val fieldId: ActivityFilter.FieldId? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "operator")
    val `operator`: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.Any? = null,

    @Json(name = "not")
    val not: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: TYPE,INDOOR,NAME,NOT_NAME,DESCRIPTION,MOVING_TIME,ELAPSED_TIME,COASTING_TIME,DISTANCE,CLIMBING,LOAD,SOURCE,RACE,AVERAGE_HEARTRATE,MAX_HEARTRATE,HRRC,AVERAGE_POWER,NORM_POWER,PACE,GAP,AVERAGE_SPEED,MAX_SPEED,VARIABILITY_INDEX,INTENSITY,AVERAGE_CADENCE,AVERAGE_CADENCE_Z2,AVERAGE_TEMP,CALORIES,WORK,WORK_ABOVE_FTP,MAX_WBAL_DEPLETION,EFFICIENCY,POWER_HR,POWER_HR_Z2,POWER_HR_Z2_MINS,RPE,FEEL,SESSION_RPE,KG_LIFTED,POWER_METER,POWER_METER_SERIAL,GEAR_NAME,TRIMP,CUSTOM,TAGS,DEVICE_NAME,COMPLIANCE,POLARIZATION_INDEX,DAY_OF_WEEK
     */
    @JsonClass(generateAdapter = false)
    enum class FieldId(val value: kotlin.String) {
        @Json(name = "type") TYPE("type"),
        @Json(name = "indoor") INDOOR("indoor"),
        @Json(name = "name") NAME("name"),
        @Json(name = "notName") NOT_NAME("notName"),
        @Json(name = "description") DESCRIPTION("description"),
        @Json(name = "moving_time") MOVING_TIME("moving_time"),
        @Json(name = "elapsed_time") ELAPSED_TIME("elapsed_time"),
        @Json(name = "coasting_time") COASTING_TIME("coasting_time"),
        @Json(name = "distance") DISTANCE("distance"),
        @Json(name = "climbing") CLIMBING("climbing"),
        @Json(name = "load") LOAD("load"),
        @Json(name = "source") SOURCE("source"),
        @Json(name = "race") RACE("race"),
        @Json(name = "average_heartrate") AVERAGE_HEARTRATE("average_heartrate"),
        @Json(name = "max_heartrate") MAX_HEARTRATE("max_heartrate"),
        @Json(name = "hrrc") HRRC("hrrc"),
        @Json(name = "average_power") AVERAGE_POWER("average_power"),
        @Json(name = "norm_power") NORM_POWER("norm_power"),
        @Json(name = "pace") PACE("pace"),
        @Json(name = "gap") GAP("gap"),
        @Json(name = "average_speed") AVERAGE_SPEED("average_speed"),
        @Json(name = "max_speed") MAX_SPEED("max_speed"),
        @Json(name = "variability_index") VARIABILITY_INDEX("variability_index"),
        @Json(name = "intensity") INTENSITY("intensity"),
        @Json(name = "average_cadence") AVERAGE_CADENCE("average_cadence"),
        @Json(name = "average_cadence_z2") AVERAGE_CADENCE_Z2("average_cadence_z2"),
        @Json(name = "average_temp") AVERAGE_TEMP("average_temp"),
        @Json(name = "calories") CALORIES("calories"),
        @Json(name = "work") WORK("work"),
        @Json(name = "work_above_ftp") WORK_ABOVE_FTP("work_above_ftp"),
        @Json(name = "max_wbal_depletion") MAX_WBAL_DEPLETION("max_wbal_depletion"),
        @Json(name = "efficiency") EFFICIENCY("efficiency"),
        @Json(name = "power_hr") POWER_HR("power_hr"),
        @Json(name = "power_hr_z2") POWER_HR_Z2("power_hr_z2"),
        @Json(name = "power_hr_z2_mins") POWER_HR_Z2_MINS("power_hr_z2_mins"),
        @Json(name = "rpe") RPE("rpe"),
        @Json(name = "feel") FEEL("feel"),
        @Json(name = "session_rpe") SESSION_RPE("session_rpe"),
        @Json(name = "kg_lifted") KG_LIFTED("kg_lifted"),
        @Json(name = "power_meter") POWER_METER("power_meter"),
        @Json(name = "power_meter_serial") POWER_METER_SERIAL("power_meter_serial"),
        @Json(name = "gear_name") GEAR_NAME("gear_name"),
        @Json(name = "trimp") TRIMP("trimp"),
        @Json(name = "custom") CUSTOM("custom"),
        @Json(name = "tags") TAGS("tags"),
        @Json(name = "device_name") DEVICE_NAME("device_name"),
        @Json(name = "compliance") COMPLIANCE("compliance"),
        @Json(name = "polarization_index") POLARIZATION_INDEX("polarization_index"),
        @Json(name = "day_of_week") DAY_OF_WEEK("day_of_week");
    }
}

