/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model

import com.github.maciej.kaznowski.intervalsicuclient.model.Anomaly

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param name 
 * @param `data` 
 * @param data2 
 * @param anomalies 
 * @param custom 
 */
@JsonClass(generateAdapter = true)

data class ActivityStream (

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "data")
    val `data`: kotlin.Any? = null,

    @Json(name = "data2")
    val data2: kotlin.Any? = null,

    @Json(name = "anomalies")
    val anomalies: kotlin.collections.List<Anomaly>? = null,

    @Json(name = "custom")
    val custom: kotlin.Boolean? = null

)

