/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param startIndex 
 * @param endIndex 
 * @param `value` 
 * @param valueEnd 
 */
@JsonClass(generateAdapter = true)

data class Anomaly (

    @Json(name = "start_index")
    val startIndex: kotlin.Int? = null,

    @Json(name = "end_index")
    val endIndex: kotlin.Int? = null,

    @Json(name = "value")
    val `value`: kotlin.Int? = null,

    @Json(name = "valueEnd")
    val valueEnd: kotlin.Int? = null

)

