/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model

import com.github.maciej.kaznowski.intervalsicuclient.model.AthleteSearchResult
import com.github.maciej.kaznowski.intervalsicuclient.model.CustomItem
import com.github.maciej.kaznowski.intervalsicuclient.model.Folder

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param athlete 
 * @param sharedFolders 
 * @param customItems 
 */
@JsonClass(generateAdapter = true)

data class AthleteProfile (

    @Json(name = "athlete")
    val athlete: AthleteSearchResult? = null,

    @Json(name = "sharedFolders")
    val sharedFolders: kotlin.collections.List<Folder>? = null,

    @Json(name = "customItems")
    val customItems: kotlin.collections.List<CustomItem>? = null

)

