/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param filename 
 * @param mimetype 
 * @param url 
 */
@JsonClass(generateAdapter = true)

data class Attachment (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "filename")
    val filename: kotlin.String? = null,

    @Json(name = "mimetype")
    val mimetype: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null

)

