/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model

import com.github.maciej.kaznowski.intervalsicuclient.model.AthleteSearchResult
import com.github.maciej.kaznowski.intervalsicuclient.model.Workout

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param athleteId 
 * @param id 
 * @param type 
 * @param name 
 * @param description 
 * @param children 
 * @param visibility 
 * @param startDateLocal 
 * @param rolloutWeeks 
 * @param autoRolloutDay 
 * @param readOnlyWorkouts 
 * @param startingCtl 
 * @param startingAtl 
 * @param activityTypes 
 * @param numWorkouts 
 * @param durationWeeks 
 * @param hoursPerWeekMin 
 * @param hoursPerWeekMax 
 * @param workoutTargets 
 * @param blurb 
 * @param canEdit 
 * @param sharedWithCount 
 * @param shareToken 
 * @param owner 
 * @param copyFolderId 
 */
@JsonClass(generateAdapter = true)

data class CreateFolderDTO (

    @Json(name = "athlete_id")
    val athleteId: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "type")
    val type: CreateFolderDTO.Type? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "children")
    val children: kotlin.collections.List<Workout>? = null,

    @Json(name = "visibility")
    val visibility: CreateFolderDTO.Visibility? = null,

    @Json(name = "start_date_local")
    val startDateLocal: kotlin.String? = null,

    @Json(name = "rollout_weeks")
    val rolloutWeeks: kotlin.Int? = null,

    @Json(name = "auto_rollout_day")
    val autoRolloutDay: kotlin.Int? = null,

    @Json(name = "read_only_workouts")
    val readOnlyWorkouts: kotlin.Boolean? = null,

    @Json(name = "starting_ctl")
    val startingCtl: kotlin.Int? = null,

    @Json(name = "starting_atl")
    val startingAtl: kotlin.Int? = null,

    @Json(name = "activity_types")
    val activityTypes: kotlin.collections.List<CreateFolderDTO.ActivityTypes>? = null,

    @Json(name = "num_workouts")
    val numWorkouts: kotlin.Int? = null,

    @Json(name = "duration_weeks")
    val durationWeeks: kotlin.Int? = null,

    @Json(name = "hours_per_week_min")
    val hoursPerWeekMin: kotlin.Int? = null,

    @Json(name = "hours_per_week_max")
    val hoursPerWeekMax: kotlin.Int? = null,

    @Json(name = "workout_targets")
    val workoutTargets: kotlin.collections.List<CreateFolderDTO.WorkoutTargets>? = null,

    @Json(name = "blurb")
    val blurb: kotlin.String? = null,

    @Json(name = "canEdit")
    val canEdit: kotlin.Boolean? = null,

    @Json(name = "sharedWithCount")
    val sharedWithCount: kotlin.Int? = null,

    @Json(name = "shareToken")
    val shareToken: kotlin.String? = null,

    @Json(name = "owner")
    val owner: AthleteSearchResult? = null,

    @Json(name = "copy_folder_id")
    val copyFolderId: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: FOLDER,PLAN
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "FOLDER") FOLDER("FOLDER"),
        @Json(name = "PLAN") PLAN("PLAN");
    }
    /**
     * 
     *
     * Values: PRIVATE,PUBLIC
     */
    @JsonClass(generateAdapter = false)
    enum class Visibility(val value: kotlin.String) {
        @Json(name = "PRIVATE") PRIVATE("PRIVATE"),
        @Json(name = "PUBLIC") PUBLIC("PUBLIC");
    }
    /**
     * 
     *
     * Values: RIDE,RUN,SWIM,WEIGHT_TRAINING,HIKE,WALK,ALPINE_SKI,BACKCOUNTRY_SKI,BADMINTON,CANOEING,CROSSFIT,E_BIKE_RIDE,E_MOUNTAIN_BIKE_RIDE,ELLIPTICAL,GOLF,GRAVEL_RIDE,HANDCYCLE,HIGH_INTENSITY_INTERVAL_TRAINING,HOCKEY,ICE_SKATE,INLINE_SKATE,KAYAKING,KITESURF,MOUNTAIN_BIKE_RIDE,NORDIC_SKI,OPEN_WATER_SWIM,PADEL,PILATES,PICKLEBALL,RACQUETBALL,RUGBY,ROCK_CLIMBING,ROLLER_SKI,ROWING,SAIL,SKATEBOARD,SNOWBOARD,SNOWSHOE,SOCCER,SQUASH,STAIR_STEPPER,STAND_UP_PADDLING,SURFING,TABLE_TENNIS,TENNIS,TRAIL_RUN,TRANSITION,VELOMOBILE,VIRTUAL_RIDE,VIRTUAL_ROW,VIRTUAL_RUN,WATER_SPORT,WHEELCHAIR,WINDSURF,WORKOUT,YOGA,OTHER
     */
    @JsonClass(generateAdapter = false)
    enum class ActivityTypes(val value: kotlin.String) {
        @Json(name = "Ride") RIDE("Ride"),
        @Json(name = "Run") RUN("Run"),
        @Json(name = "Swim") SWIM("Swim"),
        @Json(name = "WeightTraining") WEIGHT_TRAINING("WeightTraining"),
        @Json(name = "Hike") HIKE("Hike"),
        @Json(name = "Walk") WALK("Walk"),
        @Json(name = "AlpineSki") ALPINE_SKI("AlpineSki"),
        @Json(name = "BackcountrySki") BACKCOUNTRY_SKI("BackcountrySki"),
        @Json(name = "Badminton") BADMINTON("Badminton"),
        @Json(name = "Canoeing") CANOEING("Canoeing"),
        @Json(name = "Crossfit") CROSSFIT("Crossfit"),
        @Json(name = "EBikeRide") E_BIKE_RIDE("EBikeRide"),
        @Json(name = "EMountainBikeRide") E_MOUNTAIN_BIKE_RIDE("EMountainBikeRide"),
        @Json(name = "Elliptical") ELLIPTICAL("Elliptical"),
        @Json(name = "Golf") GOLF("Golf"),
        @Json(name = "GravelRide") GRAVEL_RIDE("GravelRide"),
        @Json(name = "Handcycle") HANDCYCLE("Handcycle"),
        @Json(name = "HighIntensityIntervalTraining") HIGH_INTENSITY_INTERVAL_TRAINING("HighIntensityIntervalTraining"),
        @Json(name = "Hockey") HOCKEY("Hockey"),
        @Json(name = "IceSkate") ICE_SKATE("IceSkate"),
        @Json(name = "InlineSkate") INLINE_SKATE("InlineSkate"),
        @Json(name = "Kayaking") KAYAKING("Kayaking"),
        @Json(name = "Kitesurf") KITESURF("Kitesurf"),
        @Json(name = "MountainBikeRide") MOUNTAIN_BIKE_RIDE("MountainBikeRide"),
        @Json(name = "NordicSki") NORDIC_SKI("NordicSki"),
        @Json(name = "OpenWaterSwim") OPEN_WATER_SWIM("OpenWaterSwim"),
        @Json(name = "Padel") PADEL("Padel"),
        @Json(name = "Pilates") PILATES("Pilates"),
        @Json(name = "Pickleball") PICKLEBALL("Pickleball"),
        @Json(name = "Racquetball") RACQUETBALL("Racquetball"),
        @Json(name = "Rugby") RUGBY("Rugby"),
        @Json(name = "RockClimbing") ROCK_CLIMBING("RockClimbing"),
        @Json(name = "RollerSki") ROLLER_SKI("RollerSki"),
        @Json(name = "Rowing") ROWING("Rowing"),
        @Json(name = "Sail") SAIL("Sail"),
        @Json(name = "Skateboard") SKATEBOARD("Skateboard"),
        @Json(name = "Snowboard") SNOWBOARD("Snowboard"),
        @Json(name = "Snowshoe") SNOWSHOE("Snowshoe"),
        @Json(name = "Soccer") SOCCER("Soccer"),
        @Json(name = "Squash") SQUASH("Squash"),
        @Json(name = "StairStepper") STAIR_STEPPER("StairStepper"),
        @Json(name = "StandUpPaddling") STAND_UP_PADDLING("StandUpPaddling"),
        @Json(name = "Surfing") SURFING("Surfing"),
        @Json(name = "TableTennis") TABLE_TENNIS("TableTennis"),
        @Json(name = "Tennis") TENNIS("Tennis"),
        @Json(name = "TrailRun") TRAIL_RUN("TrailRun"),
        @Json(name = "Transition") TRANSITION("Transition"),
        @Json(name = "Velomobile") VELOMOBILE("Velomobile"),
        @Json(name = "VirtualRide") VIRTUAL_RIDE("VirtualRide"),
        @Json(name = "VirtualRow") VIRTUAL_ROW("VirtualRow"),
        @Json(name = "VirtualRun") VIRTUAL_RUN("VirtualRun"),
        @Json(name = "WaterSport") WATER_SPORT("WaterSport"),
        @Json(name = "Wheelchair") WHEELCHAIR("Wheelchair"),
        @Json(name = "Windsurf") WINDSURF("Windsurf"),
        @Json(name = "Workout") WORKOUT("Workout"),
        @Json(name = "Yoga") YOGA("Yoga"),
        @Json(name = "Other") OTHER("Other");
    }
    /**
     * 
     *
     * Values: AUTO,POWER,HR,PACE
     */
    @JsonClass(generateAdapter = false)
    enum class WorkoutTargets(val value: kotlin.String) {
        @Json(name = "AUTO") AUTO("AUTO"),
        @Json(name = "POWER") POWER("POWER"),
        @Json(name = "HR") HR("HR"),
        @Json(name = "PACE") PACE("PACE");
    }
}

