/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param coefficients 
 * @param r2 
 */
@JsonClass(generateAdapter = true)

data class Curve (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "coefficients")
    val coefficients: kotlin.collections.List<kotlin.Double>? = null,

    @Json(name = "r2")
    val r2: kotlin.Double? = null

)

