/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model

import com.github.maciej.kaznowski.intervalsicuclient.model.AthleteSearchResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param athleteId 
 * @param type 
 * @param visibility 
 * @param name 
 * @param description 
 * @param image 
 * @param content 
 * @param usageCount 
 * @param index 
 * @param updated 
 * @param fromAthlete 
 * @param fromId 
 */
@JsonClass(generateAdapter = true)

data class CustomItem (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "athlete_id")
    val athleteId: kotlin.String? = null,

    @Json(name = "type")
    val type: CustomItem.Type? = null,

    @Json(name = "visibility")
    val visibility: CustomItem.Visibility? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "image")
    val image: kotlin.String? = null,

    @Json(name = "content")
    val content: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "usage_count")
    val usageCount: kotlin.Int? = null,

    @Json(name = "index")
    val index: kotlin.Int? = null,

    @Json(name = "updated")
    val updated: java.time.OffsetDateTime? = null,

    @Json(name = "from_athlete")
    val fromAthlete: AthleteSearchResult? = null,

    @Json(name = "from_id")
    val fromId: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: FITNESS_CHART,TRACE_CHART,INPUT_FIELD,ACTIVITY_FIELD,INTERVAL_FIELD,ACTIVITY_STREAM,ACTIVITY_CHART
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "FITNESS_CHART") FITNESS_CHART("FITNESS_CHART"),
        @Json(name = "TRACE_CHART") TRACE_CHART("TRACE_CHART"),
        @Json(name = "INPUT_FIELD") INPUT_FIELD("INPUT_FIELD"),
        @Json(name = "ACTIVITY_FIELD") ACTIVITY_FIELD("ACTIVITY_FIELD"),
        @Json(name = "INTERVAL_FIELD") INTERVAL_FIELD("INTERVAL_FIELD"),
        @Json(name = "ACTIVITY_STREAM") ACTIVITY_STREAM("ACTIVITY_STREAM"),
        @Json(name = "ACTIVITY_CHART") ACTIVITY_CHART("ACTIVITY_CHART");
    }
    /**
     * 
     *
     * Values: PRIVATE,FOLLOWERS,PUBLIC
     */
    @JsonClass(generateAdapter = false)
    enum class Visibility(val value: kotlin.String) {
        @Json(name = "PRIVATE") PRIVATE("PRIVATE"),
        @Json(name = "FOLLOWERS") FOLLOWERS("FOLLOWERS"),
        @Json(name = "PUBLIC") PUBLIC("PUBLIC");
    }
}

