/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param afterKj 
 * @param label 
 * @param percentile 
 * @param startDateLocal 
 * @param endDateLocal 
 * @param secs 
 * @param distance 
 * @param propertyValues 
 * @param submaxValues 
 * @param submaxActivityId 
 * @param startIndex 
 * @param endIndex 
 * @param activityId 
 */
@JsonClass(generateAdapter = true)

data class DataCurve (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "after_kj")
    val afterKj: kotlin.Int? = null,

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "percentile")
    val percentile: kotlin.Float? = null,

    @Json(name = "start_date_local")
    val startDateLocal: kotlin.String? = null,

    @Json(name = "end_date_local")
    val endDateLocal: kotlin.String? = null,

    @Json(name = "secs")
    val secs: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "distance")
    val distance: kotlin.collections.List<kotlin.Float>? = null,

    @Json(name = "values")
    val propertyValues: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "submax_values")
    val submaxValues: kotlin.collections.List<kotlin.collections.List<kotlin.Int>>? = null,

    @Json(name = "submax_activity_id")
    val submaxActivityId: kotlin.collections.List<kotlin.collections.List<kotlin.String>>? = null,

    @Json(name = "start_index")
    val startIndex: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "end_index")
    val endIndex: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "activity_id")
    val activityId: kotlin.collections.List<kotlin.String>? = null

)

