/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model

import com.github.maciej.kaznowski.intervalsicuclient.model.Activity
import com.github.maciej.kaznowski.intervalsicuclient.model.DataCurve

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param list 
 * @param activities 
 */
@JsonClass(generateAdapter = true)

data class DataCurveSetPaceCurve (

    @Json(name = "list")
    val list: kotlin.collections.List<DataCurve>? = null,

    @Json(name = "activities")
    val activities: kotlin.collections.Map<kotlin.String, Activity>? = null

)

