/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param provider 
 * @param location 
 * @param label 
 * @param lat 
 * @param lon 
 * @param enabled 
 */
@JsonClass(generateAdapter = true)

data class Forecast (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "provider")
    val provider: Forecast.Provider? = null,

    @Json(name = "location")
    val location: kotlin.String? = null,

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "lat")
    val lat: kotlin.Float? = null,

    @Json(name = "lon")
    val lon: kotlin.Float? = null,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: OPEN_WEATHER
     */
    @JsonClass(generateAdapter = false)
    enum class Provider(val value: kotlin.String) {
        @Json(name = "OPEN_WEATHER") OPEN_WEATHER("OPEN_WEATHER");
    }
}

