/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param distance 
 * @param elapsedTime 
 * @param movingTime 
 * @param activities 
 */
@JsonClass(generateAdapter = true)

data class GearStats (

    @Json(name = "distance")
    val distance: kotlin.Float? = null,

    @Json(name = "elapsed_time")
    val elapsedTime: kotlin.Float? = null,

    @Json(name = "moving_time")
    val movingTime: kotlin.Float? = null,

    @Json(name = "activities")
    val activities: kotlin.Int? = null

)

