/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model

import com.github.maciej.kaznowski.intervalsicuclient.model.ActivityFilter
import com.github.maciej.kaznowski.intervalsicuclient.model.GearReminder

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param athleteId 
 * @param type 
 * @param name 
 * @param purchased 
 * @param notes 
 * @param distance 
 * @param time 
 * @param activities 
 * @param useElapsedTime 
 * @param retired 
 * @param componentIds 
 * @param reminders 
 * @param activityFilters 
 * @param component 
 */
@JsonClass(generateAdapter = true)

data class Gear (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "athlete_id")
    val athleteId: kotlin.String? = null,

    @Json(name = "type")
    val type: Gear.Type? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "purchased")
    val purchased: kotlin.String? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    @Json(name = "distance")
    val distance: kotlin.Float? = null,

    @Json(name = "time")
    val time: kotlin.Float? = null,

    @Json(name = "activities")
    val activities: kotlin.Int? = null,

    @Json(name = "use_elapsed_time")
    val useElapsedTime: kotlin.Boolean? = null,

    @Json(name = "retired")
    val retired: kotlin.String? = null,

    @Json(name = "component_ids")
    val componentIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "reminders")
    val reminders: kotlin.collections.List<GearReminder>? = null,

    @Json(name = "activity_filters")
    val activityFilters: kotlin.collections.List<ActivityFilter>? = null,

    @Json(name = "component")
    val component: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: BIKE,SHOES,WETSUIT,ROWING_MACHINE,SKIS,SNOWBOARD,BOAT,BOARD,EQUIPMENT,ACCESSORIES,APPAREL,COMPUTER,LIGHT,BATTERY,BRAKE,BRAKE_PADS,ROTOR,DRIVETRAIN,BOTTOM_BRACKET,CASSETTE,CHAIN,CHAINRINGS,CRANKSET,DERAILLEUR,PEDALS,LEVER,CABLE,FRAME,FORK,HANDLEBAR,HEADSET,SADDLE,SEATPOST,SHOCK,STEM,AXEL,HUB,TRAINER,TUBE,TYRE,WHEEL,WHEELSET,POWER_METER,CLEATS,CYCLING_SHOES,PADDLE
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "Bike") BIKE("Bike"),
        @Json(name = "Shoes") SHOES("Shoes"),
        @Json(name = "Wetsuit") WETSUIT("Wetsuit"),
        @Json(name = "RowingMachine") ROWING_MACHINE("RowingMachine"),
        @Json(name = "Skis") SKIS("Skis"),
        @Json(name = "Snowboard") SNOWBOARD("Snowboard"),
        @Json(name = "Boat") BOAT("Boat"),
        @Json(name = "Board") BOARD("Board"),
        @Json(name = "Equipment") EQUIPMENT("Equipment"),
        @Json(name = "Accessories") ACCESSORIES("Accessories"),
        @Json(name = "Apparel") APPAREL("Apparel"),
        @Json(name = "Computer") COMPUTER("Computer"),
        @Json(name = "Light") LIGHT("Light"),
        @Json(name = "Battery") BATTERY("Battery"),
        @Json(name = "Brake") BRAKE("Brake"),
        @Json(name = "BrakePads") BRAKE_PADS("BrakePads"),
        @Json(name = "Rotor") ROTOR("Rotor"),
        @Json(name = "Drivetrain") DRIVETRAIN("Drivetrain"),
        @Json(name = "BottomBracket") BOTTOM_BRACKET("BottomBracket"),
        @Json(name = "Cassette") CASSETTE("Cassette"),
        @Json(name = "Chain") CHAIN("Chain"),
        @Json(name = "Chainrings") CHAINRINGS("Chainrings"),
        @Json(name = "Crankset") CRANKSET("Crankset"),
        @Json(name = "Derailleur") DERAILLEUR("Derailleur"),
        @Json(name = "Pedals") PEDALS("Pedals"),
        @Json(name = "Lever") LEVER("Lever"),
        @Json(name = "Cable") CABLE("Cable"),
        @Json(name = "Frame") FRAME("Frame"),
        @Json(name = "Fork") FORK("Fork"),
        @Json(name = "Handlebar") HANDLEBAR("Handlebar"),
        @Json(name = "Headset") HEADSET("Headset"),
        @Json(name = "Saddle") SADDLE("Saddle"),
        @Json(name = "Seatpost") SEATPOST("Seatpost"),
        @Json(name = "Shock") SHOCK("Shock"),
        @Json(name = "Stem") STEM("Stem"),
        @Json(name = "Axel") AXEL("Axel"),
        @Json(name = "Hub") HUB("Hub"),
        @Json(name = "Trainer") TRAINER("Trainer"),
        @Json(name = "Tube") TUBE("Tube"),
        @Json(name = "Tyre") TYRE("Tyre"),
        @Json(name = "Wheel") WHEEL("Wheel"),
        @Json(name = "Wheelset") WHEELSET("Wheelset"),
        @Json(name = "PowerMeter") POWER_METER("PowerMeter"),
        @Json(name = "Cleats") CLEATS("Cleats"),
        @Json(name = "CyclingShoes") CYCLING_SHOES("CyclingShoes"),
        @Json(name = "Paddle") PADDLE("Paddle");
    }
}

