/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param gearId 
 * @param name 
 * @param distance 
 * @param time 
 * @param activities 
 * @param days 
 * @param lastReset 
 * @param startingDistance 
 * @param startingTime 
 * @param startingActivities 
 * @param snoozedUntil 
 * @param percentUsed 
 * @param distanceUsed 
 * @param timeUsed 
 * @param activitiesUsed 
 * @param daysUsed 
 */
@JsonClass(generateAdapter = true)

data class GearReminder (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "gear_id")
    val gearId: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "distance")
    val distance: kotlin.Float? = null,

    @Json(name = "time")
    val time: kotlin.Float? = null,

    @Json(name = "activities")
    val activities: kotlin.Int? = null,

    @Json(name = "days")
    val days: kotlin.Int? = null,

    @Json(name = "last_reset")
    val lastReset: java.time.OffsetDateTime? = null,

    @Json(name = "starting_distance")
    val startingDistance: kotlin.Float? = null,

    @Json(name = "starting_time")
    val startingTime: kotlin.Float? = null,

    @Json(name = "starting_activities")
    val startingActivities: kotlin.Int? = null,

    @Json(name = "snoozed_until")
    val snoozedUntil: java.time.OffsetDateTime? = null,

    @Json(name = "percent_used")
    val percentUsed: kotlin.Float? = null,

    @Json(name = "distance_used")
    val distanceUsed: kotlin.Float? = null,

    @Json(name = "time_used")
    val timeUsed: kotlin.Float? = null,

    @Json(name = "activities_used")
    val activitiesUsed: kotlin.Int? = null,

    @Json(name = "days_used")
    val daysUsed: kotlin.Int? = null

)

