/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param icuTrainingLoad 
 * @param trainingDataCount 
 */
@JsonClass(generateAdapter = true)

data class HRLoadModel (

    @Json(name = "type")
    val type: HRLoadModel.Type? = null,

    @Json(name = "icu_training_load")
    val icuTrainingLoad: kotlin.Int? = null,

    @Json(name = "trainingDataCount")
    val trainingDataCount: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: AVG_HR,HR_ZONES,HRSS
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "AVG_HR") AVG_HR("AVG_HR"),
        @Json(name = "HR_ZONES") HR_ZONES("HR_ZONES"),
        @Json(name = "HRSS") HRSS("HRSS");
    }
}

