/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param startIndex 
 * @param endIndex 
 * @param startTime 
 * @param endTime 
 * @param startBpm 
 * @param endBpm 
 * @param averageWatts 
 * @param hrr 
 */
@JsonClass(generateAdapter = true)

data class HRRecovery (

    @Json(name = "start_index")
    val startIndex: kotlin.Int? = null,

    @Json(name = "end_index")
    val endIndex: kotlin.Int? = null,

    @Json(name = "start_time")
    val startTime: kotlin.Int? = null,

    @Json(name = "end_time")
    val endTime: kotlin.Int? = null,

    @Json(name = "start_bpm")
    val startBpm: kotlin.Int? = null,

    @Json(name = "end_bpm")
    val endBpm: kotlin.Int? = null,

    @Json(name = "average_watts")
    val averageWatts: kotlin.Int? = null,

    @Json(name = "hrr")
    val hrr: kotlin.Int? = null

)

