/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model

import com.github.maciej.kaznowski.intervalsicuclient.model.DataCurvePt

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param type 
 * @param message 
 * @param watts 
 * @param secs 
 * @param `value` 
 * @param distance 
 * @param pace 
 * @param point 
 */
@JsonClass(generateAdapter = true)

data class IcuAchievement (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "type")
    val type: IcuAchievement.Type? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "watts")
    val watts: kotlin.Int? = null,

    @Json(name = "secs")
    val secs: kotlin.Int? = null,

    @Json(name = "value")
    val `value`: kotlin.Int? = null,

    @Json(name = "distance")
    val distance: kotlin.Float? = null,

    @Json(name = "pace")
    val pace: kotlin.Float? = null,

    @Json(name = "point")
    val point: DataCurvePt? = null

) {

    /**
     * 
     *
     * Values: BEST_POWER,FTP_UP,LTHR_UP,BEST_PACE
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "BEST_POWER") BEST_POWER("BEST_POWER"),
        @Json(name = "FTP_UP") FTP_UP("FTP_UP"),
        @Json(name = "LTHR_UP") LTHR_UP("LTHR_UP"),
        @Json(name = "BEST_PACE") BEST_PACE("BEST_PACE");
    }
}

