/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param startIndex 
 * @param endIndex 
 * @param name 
 * @param segmentId 
 * @param starred 
 */
@JsonClass(generateAdapter = true)

data class IcuSegment (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "start_index")
    val startIndex: kotlin.Int? = null,

    @Json(name = "end_index")
    val endIndex: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "segment_id")
    val segmentId: kotlin.Long? = null,

    @Json(name = "starred")
    val starred: kotlin.Boolean? = null

)

