/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param startIndex 
 * @param endIndex 
 * @param power 
 * @param pace 
 * @param hr 
 */
@JsonClass(generateAdapter = true)

data class Ignore (

    @Json(name = "start_index")
    val startIndex: kotlin.Int? = null,

    @Json(name = "end_index")
    val endIndex: kotlin.Int? = null,

    @Json(name = "power")
    val power: kotlin.Boolean? = null,

    @Json(name = "pace")
    val pace: kotlin.Boolean? = null,

    @Json(name = "hr")
    val hr: kotlin.Boolean? = null

)

