/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model

import com.github.maciej.kaznowski.intervalsicuclient.model.Interval
import com.github.maciej.kaznowski.intervalsicuclient.model.IntervalGroup

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param analyzed 
 * @param icuIntervals 
 * @param icuGroups 
 */
@JsonClass(generateAdapter = true)

data class IntervalsDTO (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "analyzed")
    val analyzed: java.time.OffsetDateTime? = null,

    @Json(name = "icu_intervals")
    val icuIntervals: kotlin.collections.List<Interval>? = null,

    @Json(name = "icu_groups")
    val icuGroups: kotlin.collections.List<IntervalGroup>? = null

)

