/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bounds 
 * @param latlngs 
 */
@JsonClass(generateAdapter = true)

data class MapData (

    @Json(name = "bounds")
    val bounds: kotlin.collections.List<kotlin.collections.List<kotlin.Float>>? = null,

    @Json(name = "latlngs")
    val latlngs: kotlin.collections.List<kotlin.collections.List<kotlin.Float>>? = null

)

