/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model

import com.github.maciej.kaznowski.intervalsicuclient.model.Activity

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param athleteId 
 * @param name 
 * @param created 
 * @param type 
 * @param content 
 * @param activityId 
 * @param startIndex 
 * @param endIndex 
 * @param answer 
 * @param activity 
 * @param attachmentUrl 
 * @param attachmentMimeType 
 * @param deleted 
 * @param deletedById 
 * @param joinGroupId 
 * @param seen 
 */
@JsonClass(generateAdapter = true)

data class Message (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "athlete_id")
    val athleteId: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,

    @Json(name = "type")
    val type: Message.Type? = null,

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "activity_id")
    val activityId: kotlin.String? = null,

    @Json(name = "start_index")
    val startIndex: kotlin.Int? = null,

    @Json(name = "end_index")
    val endIndex: kotlin.Int? = null,

    @Json(name = "answer")
    val answer: kotlin.String? = null,

    @Json(name = "activity")
    val activity: Activity? = null,

    @Json(name = "attachment_url")
    val attachmentUrl: kotlin.String? = null,

    @Json(name = "attachment_mime_type")
    val attachmentMimeType: kotlin.String? = null,

    @Json(name = "deleted")
    val deleted: java.time.OffsetDateTime? = null,

    @Json(name = "deleted_by_id")
    val deletedById: kotlin.String? = null,

    @Json(name = "join_group_id")
    val joinGroupId: kotlin.Int? = null,

    @Json(name = "seen")
    val seen: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: TEXT,FOLLOW_REQ,COACH_REQ,COACH_ME_REQ,ACTIVITY,NOTE,JOIN_REQ
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "TEXT") TEXT("TEXT"),
        @Json(name = "FOLLOW_REQ") FOLLOW_REQ("FOLLOW_REQ"),
        @Json(name = "COACH_REQ") COACH_REQ("COACH_REQ"),
        @Json(name = "COACH_ME_REQ") COACH_ME_REQ("COACH_ME_REQ"),
        @Json(name = "ACTIVITY") ACTIVITY("ACTIVITY"),
        @Json(name = "NOTE") NOTE("NOTE"),
        @Json(name = "JOIN_REQ") JOIN_REQ("JOIN_REQ");
    }
}

