/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param maxBpm 
 * @param minBpm 
 * @param secs 
 * @param cumulativeSecs 
 */
@JsonClass(generateAdapter = true)

data class Plot (

    @Json(name = "max_bpm")
    val maxBpm: kotlin.Int? = null,

    @Json(name = "min_bpm")
    val minBpm: kotlin.Int? = null,

    @Json(name = "secs")
    val secs: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "cumulative_secs")
    val cumulativeSecs: kotlin.collections.List<kotlin.Int>? = null

)

