/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param athleteId 
 * @param start 
 * @param end 
 * @param minWatts 
 * @param maxWatts 
 * @param bucketSize 
 * @param bpm 
 * @param cadence 
 * @param minutes 
 * @param lthr 
 * @param maxHr 
 * @param ftp 
 */
@JsonClass(generateAdapter = true)

data class PowerHRCurve (

    @Json(name = "athleteId")
    val athleteId: kotlin.String? = null,

    @Json(name = "start")
    val start: kotlin.String? = null,

    @Json(name = "end")
    val end: kotlin.String? = null,

    @Json(name = "minWatts")
    val minWatts: kotlin.Int? = null,

    @Json(name = "maxWatts")
    val maxWatts: kotlin.Int? = null,

    @Json(name = "bucketSize")
    val bucketSize: kotlin.Int? = null,

    @Json(name = "bpm")
    val bpm: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "cadence")
    val cadence: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "minutes")
    val minutes: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "lthr")
    val lthr: kotlin.Int? = null,

    @Json(name = "max_hr")
    val maxHr: kotlin.Int? = null,

    @Json(name = "ftp")
    val ftp: kotlin.Int? = null

)

