/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.maciej.kaznowski.intervalsicuclient.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param profileMedium 
 * @param city 
 * @param state 
 * @param country 
 * @param timezone 
 * @param sex 
 * @param bio 
 * @param website 
 * @param email 
 * @param canEdit 
 */
@JsonClass(generateAdapter = true)

data class SharedWith (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "profile_medium")
    val profileMedium: kotlin.String? = null,

    @Json(name = "city")
    val city: kotlin.String? = null,

    @Json(name = "state")
    val state: kotlin.String? = null,

    @Json(name = "country")
    val country: kotlin.String? = null,

    @Json(name = "timezone")
    val timezone: kotlin.String? = null,

    @Json(name = "sex")
    val sex: kotlin.String? = null,

    @Json(name = "bio")
    val bio: kotlin.String? = null,

    @Json(name = "website")
    val website: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "canEdit")
    val canEdit: kotlin.Boolean? = null

)

